include(
    ":director",
    ":director-activitycallbacks",
    ":director-androidx-lifecycle",
    ":director-common",
    ":director-dialog",
    ":director-fragmenthost",
    ":director-retained",
    ":director-scopes",
    ":director-testing",
    ":director-traveler",
    ":director-viewpager",
    ":director-viewpager2",
    ":sample"
)