include(
    ":director",
    ":director-arch-lifecycle",
    ":director-common",
    ":director-dialog",
    ":director-scopes",
    ":director-testing",
    ":director-traveler",
    ":director-viewpager",
    ":sample"
)